---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: coreyja/rust-cache
      auto_tag: true
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
