---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: coreyja/rust-cache
      purge: true
      auto_tag: true
      auto_tag_suffix: ruby
      dry_run: true
      dockerfile: dockerfiles/ruby.Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
---
kind: signature
hmac: f10364b068a2a5d78f71ec478196ec7f8663c4143a4e19a50de2e055d2da513c

...
