---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-ruby-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: ruby
    dockerfile: cache-types/ruby/Dockerfile
    password:
      from_secret: docker_hub_password
    repo: coreyja/rust-cache
    username:
      from_secret: docker_hub_username

- name: build-yarn-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: yarn
    dockerfile: cache-types/yarn/Dockerfile
    password:
      from_secret: docker_hub_password
    purge: true
    repo: coreyja/rust-cache
    username:
      from_secret: docker_hub_username

---
kind: signature
hmac: cccb4648ba7d21cfaaa5d47fa852a0dfaaa11ee5a2717cfaf5b082dcca48c2db

...
