---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: coreyja/rust-cache
      purge: true
      auto_tag: true
      auto_tag_suffix: ruby
      dockerfile: dockerfiles/ruby.Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
---
kind: signature
hmac: 1d83ea2429585ae8dd7f08fe92e144e89062fa4a2be86440aacc02c33508ccfe

...
