---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-base-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: base
    dockerfile: Dockerfile
    password:
      from_secret: docker_hub_password
    purge: true
    repo: coreyja/rust-cache
    username:
      from_secret: docker_hub_username
  depends_on:
  - clone

- name: build-ruby-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: ruby
    dockerfile: cache-types/ruby/Dockerfile
    password:
      from_secret: docker_hub_password
    purge: true
    repo: coreyja/rust-cache
    username:
      from_secret: docker_hub_username
  depends_on:
  - build-base-docker-image

- name: build-yarn-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: yarn
    dockerfile: cache-types/yarn/Dockerfile
    password:
      from_secret: docker_hub_password
    purge: true
    repo: coreyja/rust-cache
    username:
      from_secret: docker_hub_username
  depends_on:
  - build-base-docker-image

---
kind: signature
hmac: 9ab7485ae2ada68b9dbc02285e984e9c07c40ab19e39ae1cb1f4f10710d79fd7

...
