---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build-ruby-docker-image
    image: plugins/docker
    settings:
      repo: coreyja/rust-cache
      purge: true
      auto_tag: true
      auto_tag_suffix: ruby
      dockerfile: cache-types/ruby/Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
  - name:build-yarn-docker-image
    image: plugins/docker
    settings:
      repo: coreyja/rust-cache
      purge: true
      auto_tag: true
      auto_tag_suffix: yarn
      dockerfile: cache-types/yarn/Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
---
kind: signature
hmac: 195cd7b97148f0fb2e95405c25eb5538e2c52a3439dfdc6394c75e1c4d8055a5

...
