[package]
name = "rust-cache"
version = "0.1.0"
authors = ["Corey Alexander <coreyja@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = '1.0.7'
rusoto_core = '0.38.0'
rusoto_s3 = '0.38.0'
tar = '0.4.22'
futures = ''
strfmt = '0.1.6'
